name: user_repository
description: UserRepository example for flutter_login.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  http: ^0.12.0+4
  hive: ^1.4.1+1
  system_info: ^0.1.2
  basic_utils: 2.3.4
  encrypt: ^4.0.0
  pointycastle: ^1.0.2
